### ISSUE TITLE
Missing python scripts

### ISSUE THREAD

**Issue by AnxietyVendor** [sh0416/clrcmd#1]
Excuse me, I run `python -m examples.run_train --data-dir data --model bert-rcmd` to launch training but something went wrong. 

I found this is because STSTrainer but I cannot locate clrcmd.models and clrcmd.trainer.

**Comment by sh0416** [comment]
Maybe you should install the package using `python setup.py develop`.
I recommend you using virtual environment through `virtualenv` or `python -m venv` or anaconda.
