### ISSUE TITLE
Problem with testing iSTS

### ISSUE THREAD

**Issue by MLKoz** [sh0416/clrcmd#4]
Hi, during executing `python -m examples.run_evaluate_ists --data-dir data/ISTS/test_goldStandard/ --source images --checkpoint-dir checkpoints/bert-rcmd/` I have : `FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/bert-rcmd/model_args.json'`. I cannot find model_args.json / checkpoints directory anywhere, could you help me?

**Comment by MLKoz** [comment]
Thank you so much, maybe can you tell me why you conducted experiments only on BERT and RoBERTa? Could you tell me whether using XLNet or DeBERTa improve the results on examined NLP tasks? I can read that XLNet is better than BERT on many tasks and I would like to know if your nice idea can work even better with XLNet

**Comment by sh0416** [comment]
I expect the results using XLNet and DeBERTa might not show different trends compared with the results using BERT and RoBERTa which are the widely used pretrained models in this community.
It could report the state-of-the-art performance, but it is less likely to get other insights from these pretrained models.
Also, DeBERTa and XLNet have some burden of understanding the different architecture and pretrained objective, which is not preferred for my taste.. :)

Nevertheless, you can do it if you want. OoMMix is architecture independent if the architecture provides token embeddings.
