### ISSUE TITLE
bash for ists

### ISSUE THREAD

**Issue by nurulchamidah** [sh0416/clrcmd#6]
download_ists.sh remaining empty after bash, it only create folder ISTS. could you please fix this or provide another source?
thanks

**Comment by sh0416** [comment]
Yeap, I will check and correct ASAP.

**Comment by sh0416** [comment]
I think the download source is working correctly. Could you check your environment such as supporting tar extraction?

**Comment by nurulchamidah** [comment]
ok, i already downloaded it manually from the link in the provided bash. idk because sts bash working for me.
what is the minimum hardware requirement, for example minimum memory for GPU?
i am sorry bcs i am newbie and currently learning. is there possible to change the loss function such as contrastive loss? or it is unnecessary?
thanks

**Comment by sh0416** [comment]
I conduct experiments in NVIDIA Titan Xp 12GB.
You can find better objective.

**Comment by nurulchamidah** [comment]
ok. thanks
